language: go

go:
   - "master"
   - "1.11.x"

go_import_path: github.com/fvdveen/mu2

script: 
  - GOPATH="" go mod download
  - GOPATH="" go mod vendor
  - if [[ -z "$(go version | grep '1\.9')" ]]; then go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...; else go test -v ./...; fi
  - go build ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)