version: "3"

services:
  consul1:
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
    image: consul:latest
    networks:
      - "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    restart: "always"
    volumes:
      - "./data/consul/1:/consul/data"
  consul2:
    command: "agent -server -retry-join consul1 -client 0.0.0.0"
    depends_on:
      - "consul1"
    image: consul:latest
    networks:
      - "consul"
    restart: "always"
    volumes:
      - "./data/consul/2:/consul/data"
  postgres:
    environment: 
      POSTGRES_PASSWORD: "mu2"
      POSTGRES_USER: "mu2"
    image: "postgres:latest"
    networks:
      - "db"
    restart: "always"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  bot:
    build: .
    command: ./mu2 --consul-addr=consul1:8500
    depends_on:
      - "consul1"
      - "consul2"
      - "postgres"
    environment:
      - MU2_CONSUL_ADDRESS=consul1:8500
    networks:
      - "consul"
      - "db"
    restart: "always"

networks:
  consul:
  db:
